export const IPC = {
  boot: 'ling:boot',
  theme: 'ling:theme',
  themeChanged: 'ling:theme-changed',
  credentialTheme: 'ling:credential-theme',
  tray: 'ling:tray',
  notify: 'ling:notify',
  openTask: 'ling:open-task',
  openExternal: 'ling:open-external',
  failed: 'ling:failed',
  directory: 'ling:directory',
  workspaceGit: 'ling:workspace-git',
  workspaceBranch: 'ling:workspace-branch',
  workspaceTools: 'ling:workspace-tools',
  serverStatus: 'ling:server-status',
  serverInspect: 'ling:server-inspect',
  serverProbe: 'ling:server-probe',
  serverDirectories: 'ling:server-directories',
  serverCredentials: 'ling:server-credentials',
  serverForget: 'ling:server-forget',
  credentialInfo: 'ling:credential-info',
  credentialInspect: 'ling:credential-inspect',
  credentialTrust: 'ling:credential-trust',
  credentialPassword: 'ling:credential-password',
  credentialChooseKey: 'ling:credential-choose-key',
  credentialSaveKey: 'ling:credential-save-key',
  credentialClear: 'ling:credential-clear',
  credentialTest: 'ling:credential-test',
  credentialClose: 'ling:credential-close',
  credentialResize: 'ling:credential-resize',
} as const

export const APP_URL = 'dsh-app://app/'
